// canvasjs-react-sample/src/App.js
import React, { Component } from 'react';
import CanvasJSReact from './assets/canvasjs.react';
//var CanvasJSReact = require('./assets/canvasjs.react').default;
console.log(CanvasJSReact)
var CanvasJS = CanvasJSReact.CanvasJS;
var CanvasJSChart = CanvasJSReact.CanvasJSChart;

class App extends Component {	
  render() {
	const options = {
	  theme: "light2",
	  animationEnabled: true,
	  exportEnabled: true,
	  title: {
		text: "Basic Column Chart in React"
	  },
	  data: [{				
			type: "column",
			dataPoints: [
				{ label: "Apple",  y: 10  },
				{ label: "Orange", y: 15  },
				{ label: "Banana", y: 25  },
				{ label: "Mango",  y: 30  },
				{ label: "Grape",  y: 28  }
			]
	   }]
   }
   
   const style = {
	   width: "80%",
	   height: "360px",
	   margin: "auto"
   }
		
   return (
	  <div>
		<CanvasJSChart options = {options} containerProps = {style}
			/* onRef = {ref => this.chart = ref} */
		/>
	  </div>
	);
  }
}



export default App;

// canvasjs-angular-sample/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import * as CanvasJS from '../assets/canvasjs.min';
//var CanvasJS = require('../assets/canvasjs.min');

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent implements OnInit {
	ngOnInit() {
		let chart = new CanvasJS.Chart("chartContainer", {
		theme: "light2",
		animationEnabled: true,
		exportEnabled: true,
		title: {
			text: "Basic Column Chart in Angular"
		},
		data: [{
			type: "column",
			dataPoints: [
				{ y: 71, label: "Apple" },
				{ y: 55, label: "Mango" },
				{ y: 50, label: "Orange" },
				{ y: 65, label: "Banana" },
				{ y: 95, label: "Pineapple" },
				{ y: 68, label: "Pears" },
				{ y: 28, label: "Grapes" },
				{ y: 34, label: "Lychee" },
				{ y: 14, label: "Jackfruit" }
			]
		}]
	});
		
	chart.render();
    }
}
